### ISSUE TITLE
OAuth "access_token" fields blow away custom upfront fields.

### ISSUE THREAD

**Issue by bryanhelmig** [zapier/zapier-platform-core#31]
For example, if a user has a custom field for oauth like `"baseURL"`, the final `authData` after we get the access token for the created authentication will not be `{"baseURL": "https://example.com", "access_token": "12345"}` like we would expect, instead it will be `{"access_token": "12345"}`.

**Comment by bryanhelmig** [comment]
It would be nice to properly document this too while we're at it:

https://zapier.github.io/zapier-platform-cli/#oauth2 doesn't list the extra `fields` key but we need to support it - similar to the `fields` key in https://zapier.github.io/zapier-platform-cli/#custom.

**Comment by FrancisBourgault** [comment]
Hey there, I'll provide the informations I found while trying to fix this issue.
This issue could happen with other auth type (I didn't test it though)

- The auth fields are working with custom auth. (OK)
- The auth fields with oauth2 will be stored inside the **bundle.inputData** object during the oauth2 process (**authorizeUrl** and **getAccessToken** functions). This behavior seems a bit weird since the auth fields will be store later in the bundle.authData object. This become confusing when using before and after http middleware. (Not OK, but not critical)
- During the oauth2 process, some fields will be added to the **bundle.inputData** object (redirect_uri, state, etc...). The auth fields store in the **bundle.inputData** won't be override by them, so that part is OK.
- After the oauth2 process, the test function won't be called (Don't know if it's OK or not). On Zapier web app, this will say that the account is valid. (OK)
- When the user of the Zapier web app click the "Test" button next to the account, the test function will be called and then the before http middleware. This is where it crash since the auth fields are no longer in the **bundle.authData** nor in the **bundle.inputData**. (Error)

I suspect that Zapier **SET** the value of the bundle.authData object just after the **getAccessToken** function and then Zapier only validate the account if an access_token was returned (not validating if the required auth fields are still in the **bundle.authData** object).

Zapier should **ADD** the oauth fields to the **bundle.authData** object while keeping the auth fields.

This is all the informations I have. Thanks for creating the issues. Now just a quick question: Is Zapier support for developper or only normal user?

**Comment by genecyber** [comment]
If the custom fields have default values, they will be persisted throughout within the authData but not the values entered only the values defined as default.

**Comment by genecyber** [comment]
Any movement on this?

**Comment by BrunoBernardino** [comment]
Sorry about the delay here @genecyber ! I'll look into this this week (maybe even today) and add any update as soon as I have it.

**Comment by BrunoBernardino** [comment]
I have a PR ready for review in the backend for this, and after that's merged I'll add some documentation to this repo on the `fields`. It will not require a CLI version upgrade.

**Comment by BrunoBernardino** [comment]
The issue should be fixed but I'm reopening so I remember to add the documentation bits ;)
