### ISSUE TITLE
Explanation of Paging concept in Zapier

### ISSUE THREAD

**Issue by raffaeu** [zapier/zapier-platform-core#42]
> Hi guys, first of all I want to say that the `zapier cli` is really a bit step forward for me compared to the previous framework. I just can play with all my triggers, searches and create and test everything using `mocha` and `istanbul`. 👍 

Now, the question is about **Pagination** and `trigger` or `search`.
We expose our data via `odata v 4.0` and at the moment inside our `trigger` we provide multiple options to our users such as: `order by`, `filter`, `expand`.
The problem is that every time a new record is available, actually Zapier is calling an HTTP endpoint which returns all records because there is not a concept of `pagination`; this can be a counterproductive solution (*imagine if I have thousands of records*).

What should be the solution? Returning the top 50/100 records order by *Creation Date DESCENDING* but wouldn't be this solution take the risk of loosing some records, which may have been created since the last Zap?

I have found something on this link but it doesn't really explain how the User can interact with `meta`
https://github.com/zapier/zapier-platform-cli/blob/master/README.md#bundlemeta

**Comment by raffaeu** [comment]
**Example**

If I do run a `search` and I output in the Console the `bundle.meta` using this code:

```javascript
// log in case of problems
z.console.log('Here are the input fields', bundle.inputData);
z.console.log('Here is the URL requested', url);
z.console.log('Here is the bundle Meta', bundle.meta);
```

This is what Zapier returns to me:

```javascript
== Log
Here is the bundle Meta { frontend: true,
  standard_poll: true,
  prefill: false,
  test_poll: false,
  limit: -1,
  hydrate: true,
  first_poll: false,
  page: 0 }
```

So what I want to understand is, how do we control `bundle.meta.page` and `bundle.meta.limit` or, who is in charge of controlling these two settings?

**Comment by drinchev** [comment]
Hey guys, it's been almost 2 months since this question was asked. Is there any progress about it? I'm trying to create a Polling trigger with pagination, but I'm stuck with the same problems as @raffaeu.

**Comment by xavdid** [comment]
@raffaeu @drinchev Hey, sorry about the delay here! We're still working out kinks with our process for attending to CLI issues We don't check this repo for issues nearly as often, but we'll work to improve on that. 

Paging is used in the UI when a user is navigating a dynamic dropdown across what is expected to be a lot of objects. From an implementation side, if your API supports paging, you can use this as a marker to fetch a new set of results; you never change it directly, but use it (usually) to set a param for a request. Most commonly, you might combine it with a param like `offset` (say `50 * bundle.meta.page`) so that whatever page the user is on (and we set `.page` to), your app can return fresh values. Again, this is only for use in dynamic dropdowns that might contain a ton of items. If a trigger is used as a regular trigger (to see if there are any objects to act on) we only check page 0.

Separately, your question about what to return in a poll. The guiding light is that you don't want to potentially miss any objects (like you said). Most zaps poll at 5 or 15 minute intervals (though that can stretch during outages). If you poll and get all objects, you can safely filter to only objects created in the last 2 hours (though if you experience a lot of outages, more time back wouldn't hurt). You can also just throw the entire payload at the deduper and let it figure it out. That'll work until your payload size crosses 6mb (a lambda limit), at which point those extra large triggers will error. 

As for search, there's no paging there. You can return an array of 0, 1, or many objects, but we only look at the first item (see [Return Types](https://github.com/zapier/zapier-platform-cli#return-types)), so try to put your best foot forward. 

Does that clear up some of the mystery?

**Comment by raffaeu** [comment]
@xavdid Honestly speaking we opened a thread on 11th of July, I truly appreciate the effort of your answer but as *14th of October*, which means *3 months* later, the answer is just informational for me.
Btw, still it is not what we were asking for. Pagination is useful on huge amount of data which usually occurs during synchronization and not in lookup APIs used for ComboBoxes or Searches, so no unfortunately the detailed explanation doesn't bring too much value because it is not implemented as we were expecting.

**Comment by bryanhelmig** [comment]
@raffaeu absolutely -- we've added an [issue template](https://github.com/zapier/zapier-platform-core/commit/d3d467f140d7e249e968de830c51b19e267d844f) to redirect folks to the proper repository. We also have a Slack room for real time help. Sorry about the 3 month delay here.
